trigger:
- master

pr:
- '*'

variables:
- name: BUILD_COUNTER
  value: $[counter('buildnumber', 0)]

pool:
  vmImage: windows-latest
steps:
- task: UseDotNet@2
  displayName: Install .NET Core 3.1
  inputs:
    version: 3.1.x
- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    configuration: Release
    packDirectory: $(build.artifactStagingDirectory)
- publish: $(build.artifactStagingDirectory)
  artifact: Packages
  displayName: Publish artifacts
